### ISSUE TITLE
Issue with reset-dkim on Windows

### ISSUE THREAD

**Issue by surgicalcoder** [pethin/email-svc#3]
When running reset-dkim on windows, I get the following error:

`npm run reset-dkim

> email-svc@0.0.0 reset-dkim
> node scripts/reset-dkim.js

file:///(path)email-svc-main/scripts/reset-dkim.js:36
        console.error(`Error setting private key secret.\n${wrangler.output[2]}`);
                                                                           ^

TypeError: Cannot read properties of null (reading '2')
    at file:///(path)/email-svc-main/scripts/reset-dkim.js:36:69

Node.js v20.3.0`

After some digging (I have next to no knowledge of node), Line 31, the call to `npm` needs to be replaced with `npm.cmd`, then it appears to work.

**Comment by pethin** [comment]
Thanks for the heads up. I'm using a Mac. I've made an update to the scripts to use `process.argv[0]` instead of `npm`. That should work on any OS. Try it out and let me know if it works.
